//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPro2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\chb63\\\\Desktop\\\\אופיר\\\\")]
        public string jsonDir {
            get {
                return ((string)(this["jsonDir"]));
            }
            set {
                this["jsonDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0101")]
        public string dbCode {
            get {
                return ((string)(this["dbCode"]));
            }
            set {
                this["dbCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\\\\\\\tigger\\\\ophir\\\\Optics\\\\mfg\\\\coatings\\\\Machines\\\\E\\\\in\\\\PCB32\\\\rec\"")]
        public string dbMachineE {
            get {
                return ((string)(this["dbMachineE"]));
            }
            set {
                this["dbMachineE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\\\\\\\tigger\\\\ophir\\\\Optics\\\\mfg\\\\coatings\\\\Machines\\\\N\\\\IN\\\\rec\"")]
        public string dbMachineN {
            get {
                return ((string)(this["dbMachineN"]));
            }
            set {
                this["dbMachineN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\\\\\\\tigger\\\\ophir\\\\Optics\\\\mfg\\\\coatings\\\\Machines\\\\P\\\\IN\\\\rec\"")]
        public string dbMachineP {
            get {
                return ((string)(this["dbMachineP"]));
            }
            set {
                this["dbMachineP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\\\\\\\tigger\\\\ophir\\\\Optics\\\\mfg\\\\coatings\\\\Machines\\\\X\\\\IN\\\\REC\"")]
        public string dbMachineX {
            get {
                return ((string)(this["dbMachineX"]));
            }
            set {
                this["dbMachineX"] = value;
            }
        }
    }
}
